version: "3.9"
services:
  front:
    build:
      context: ./app-front
      dockerfile: ./Dockerfile.dev
      args:
        NODE_AUTH_TOKEN: $NODE_AUTH_TOKEN

    ports:
    - 3000:3000

    volumes:
    - ./app-front:/app
    - /app/node_modules

    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 5
        window: 10s

  auth:
    build:
      context: ./auth-microservice
      dockerfile: ./Dockerfile.dev
      args:
        NODE_AUTH_TOKEN: $NODE_AUTH_TOKEN

    volumes:
    - ./auth-microservice:/app
    - /app/node_modules

    environment:
    - PORT=80
    - DB_HOST=db
    - DB_PORT=3306
    - DB_USER=greenmile
    - DB_PASSWORD=$DB_PASSWORD
    - DB_DATABASE=greenmile

    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 5
        window: 10s

  calculator:
    build:
      context: ./calculator-microservice
      dockerfile: ./Dockerfile.dev
      args:
        NODE_AUTH_TOKEN: $NODE_AUTH_TOKEN

    volumes:
    - ./calculator-microservice:/app
    - /app/node_modules

    environment:
    - PORT=80
    - DB_HOST=db
    - DB_PORT=3306
    - DB_USER=greenmile
    - DB_PASSWORD=$DB_PASSWORD
    - DB_DATABASE=greenmile

    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 5
        window: 10s

  data:
    build:
      context: ./data-microservice
      dockerfile: ./Dockerfile.dev
      args:
        NODE_AUTH_TOKEN: $NODE_AUTH_TOKEN

    volumes:
    - ./data-microservice:/app
    - /app/node_modules

    environment:
    - PORT=80
    - DB_HOST=db
    - DB_PORT=3306
    - DB_USER=greenmile
    - DB_PASSWORD=$DB_PASSWORD
    - DB_DATABASE=greenmile

    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 5
        window: 10s

  challenges:
    build:
      context: ./challenges-microservice
      dockerfile: ./Dockerfile.dev
      args:
        NODE_AUTH_TOKEN: $NODE_AUTH_TOKEN

    volumes:
    - ./challenges-microservice:/app
    - /app/node_modules

    environment:
    - PORT=80
    - DB_HOST=db
    - DB_PORT=3306
    - DB_USER=greenmile
    - DB_PASSWORD=$DB_PASSWORD
    - DB_DATABASE=greenmile

    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 5
        window: 10s

  db:
    image: mariadb:latest
    pull_policy: missing

    ports:
    - 3307:3306

    volumes:
    - db_data:/var/lib/mysql
    - db_config:/etc/mysql/conf.d

    environment:
    - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
    - MYSQL_USER=greenmile
    - MYSQL_PASSWORD=$DB_PASSWORD
    - MYSQL_DATABASE=greenmile

    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 5
        window: 10s

volumes:
  db_data:
  db_config:
